apiVersion: v1
kind: Service
metadata:
  name: grafana-nodeport-svc
  namespace: monitoring
spec:
  type: NodePort
  ports:
  - name: web
    nodePort: 30900
    port: 3000
    protocol: TCP
    targetPort: web
  selector:
    app: kube-prometheus-grafana
